# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nuevoJuzgado.ui'
#
# Created: Wed Jan 25 15:09:20 2012
#      by: pyside-uic 0.2.13 running on PySide 1.0.8
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_NuevoJuzgado(object):
    def setupUi(self, NuevoJuzgado):
        NuevoJuzgado.setObjectName("NuevoJuzgado")
        NuevoJuzgado.resize(407, 250)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NuevoJuzgado.sizePolicy().hasHeightForWidth())
        NuevoJuzgado.setSizePolicy(sizePolicy)
        NuevoJuzgado.setMaximumSize(QtCore.QSize(16777215, 250))
        self.gridLayout = QtGui.QGridLayout(NuevoJuzgado)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtGui.QDialogButtonBox(NuevoJuzgado)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.line = QtGui.QFrame(NuevoJuzgado)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(NuevoJuzgado)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.lblNombre = QtGui.QLabel(self.groupBox)
        self.lblNombre.setObjectName("lblNombre")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblNombre)
        self.txtNombre = QtGui.QLineEdit(self.groupBox)
        self.txtNombre.setObjectName("txtNombre")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtNombre)
        self.lblCiudad = QtGui.QLabel(self.groupBox)
        self.lblCiudad.setObjectName("lblCiudad")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblCiudad)
        self.txtCiudad = QtGui.QLineEdit(self.groupBox)
        self.txtCiudad.setObjectName("txtCiudad")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtCiudad)
        self.lblDireccion = QtGui.QLabel(self.groupBox)
        self.lblDireccion.setObjectName("lblDireccion")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblDireccion)
        self.txtDireccion = QtGui.QLineEdit(self.groupBox)
        self.txtDireccion.setObjectName("txtDireccion")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtDireccion)
        self.lblTelefono = QtGui.QLabel(self.groupBox)
        self.lblTelefono.setObjectName("lblTelefono")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblTelefono)
        self.txtTelefono = QtGui.QLineEdit(self.groupBox)
        self.txtTelefono.setObjectName("txtTelefono")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtTelefono)
        self.lblTipo = QtGui.QLabel(self.groupBox)
        self.lblTipo.setObjectName("lblTipo")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblTipo)
        self.txtTipo = QtGui.QLineEdit(self.groupBox)
        self.txtTipo.setObjectName("txtTipo")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtTipo)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.btnAdd = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdd.sizePolicy().hasHeightForWidth())
        self.btnAdd.setSizePolicy(sizePolicy)
        self.btnAdd.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout_2.addWidget(self.btnAdd, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.lblNombre.setBuddy(self.txtNombre)
        self.lblCiudad.setBuddy(self.txtCiudad)
        self.lblDireccion.setBuddy(self.txtDireccion)
        self.lblTelefono.setBuddy(self.txtTelefono)
        self.lblTipo.setBuddy(self.txtTipo)

        self.retranslateUi(NuevoJuzgado)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), NuevoJuzgado.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), NuevoJuzgado.reject)
        QtCore.QMetaObject.connectSlotsByName(NuevoJuzgado)
        NuevoJuzgado.setTabOrder(self.txtNombre, self.txtCiudad)
        NuevoJuzgado.setTabOrder(self.txtCiudad, self.txtDireccion)
        NuevoJuzgado.setTabOrder(self.txtDireccion, self.txtTelefono)
        NuevoJuzgado.setTabOrder(self.txtTelefono, self.txtTipo)
        NuevoJuzgado.setTabOrder(self.txtTipo, self.btnAdd)
        NuevoJuzgado.setTabOrder(self.btnAdd, self.buttonBox)

    def retranslateUi(self, NuevoJuzgado):
        NuevoJuzgado.setWindowTitle(QtGui.QApplication.translate("NuevoJuzgado", "Nuevo juzgado", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("NuevoJuzgado", "Ingrese la información del nuevo juzgado:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNombre.setText(QtGui.QApplication.translate("NuevoJuzgado", "Nombre:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCiudad.setText(QtGui.QApplication.translate("NuevoJuzgado", "Ciudad:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDireccion.setText(QtGui.QApplication.translate("NuevoJuzgado", "Dirección", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTelefono.setText(QtGui.QApplication.translate("NuevoJuzgado", "Teléfono", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTipo.setText(QtGui.QApplication.translate("NuevoJuzgado", "Tipo", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("NuevoJuzgado", "+", None, QtGui.QApplication.UnicodeUTF8))

