# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nuevaPersona.ui'
#
# Created: Wed Mar 21 19:22:47 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_NuevaPersona(object):
    def setupUi(self, NuevaPersona):
        NuevaPersona.setObjectName("NuevaPersona")
        NuevaPersona.resize(304, 317)
        self.gridLayout = QtGui.QGridLayout(NuevaPersona)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(NuevaPersona)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.txtNombre = QtGui.QLineEdit(self.groupBox)
        self.txtNombre.setObjectName("txtNombre")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtNombre)
        self.txtCedula = QtGui.QLineEdit(self.groupBox)
        self.txtCedula.setObjectName("txtCedula")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtCedula)
        self.txtTelefono = QtGui.QLineEdit(self.groupBox)
        self.txtTelefono.setObjectName("txtTelefono")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtTelefono)
        self.txtDireccion = QtGui.QLineEdit(self.groupBox)
        self.txtDireccion.setObjectName("txtDireccion")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtDireccion)
        self.txtCorreo = QtGui.QLineEdit(self.groupBox)
        self.txtCorreo.setObjectName("txtCorreo")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtCorreo)
        self.verticalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.txtNotas = QtGui.QTextEdit(self.groupBox)
        self.txtNotas.setObjectName("txtNotas")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtNotas)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.btnAdd = QtGui.QPushButton(NuevaPersona)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdd.sizePolicy().hasHeightForWidth())
        self.btnAdd.setSizePolicy(sizePolicy)
        self.btnAdd.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout.addWidget(self.btnAdd, 1, 0, 1, 1)
        self.line = QtGui.QFrame(NuevaPersona)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(NuevaPersona)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)

        self.retranslateUi(NuevaPersona)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), NuevaPersona.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), NuevaPersona.reject)
        QtCore.QMetaObject.connectSlotsByName(NuevaPersona)

    def retranslateUi(self, NuevaPersona):
        NuevaPersona.setWindowTitle(QtGui.QApplication.translate("NuevaPersona", "Nueva Persona", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("NuevaPersona", "Ingrese la información de la nueva persona:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NuevaPersona", "Nombre:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("NuevaPersona", "Cédula:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("NuevaPersona", "Teléfono:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("NuevaPersona", "Dirección:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("NuevaPersona", "Correo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("NuevaPersona", "Notas:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("NuevaPersona", "+", None, QtGui.QApplication.UnicodeUTF8))

