# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/asistenteImpresion.ui'
#
# Created: Fri Oct 19 09:59:03 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AsistenteImpresionDialog(object):
    def setupUi(self, AsistenteImpresionDialog):
        AsistenteImpresionDialog.setObjectName("AsistenteImpresionDialog")
        AsistenteImpresionDialog.resize(573, 307)
        self.verticalLayout_3 = QtGui.QVBoxLayout(AsistenteImpresionDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(AsistenteImpresionDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rdProceso = QtGui.QRadioButton(self.groupBox)
        self.rdProceso.setObjectName("rdProceso")
        self.verticalLayout.addWidget(self.rdProceso)
        self.rdDemandante = QtGui.QRadioButton(self.groupBox)
        self.rdDemandante.setObjectName("rdDemandante")
        self.verticalLayout.addWidget(self.rdDemandante)
        self.rdDemandado = QtGui.QRadioButton(self.groupBox)
        self.rdDemandado.setObjectName("rdDemandado")
        self.verticalLayout.addWidget(self.rdDemandado)
        self.rdJuzgado = QtGui.QRadioButton(self.groupBox)
        self.rdJuzgado.setObjectName("rdJuzgado")
        self.verticalLayout.addWidget(self.rdJuzgado)
        self.rdQR = QtGui.QRadioButton(self.groupBox)
        self.rdQR.setObjectName("rdQR")
        self.verticalLayout.addWidget(self.rdQR)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rdListadoProcesos = QtGui.QRadioButton(self.groupBox)
        self.rdListadoProcesos.setObjectName("rdListadoProcesos")
        self.verticalLayout_2.addWidget(self.rdListadoProcesos)
        self.rdListadoDemandantes = QtGui.QRadioButton(self.groupBox)
        self.rdListadoDemandantes.setObjectName("rdListadoDemandantes")
        self.verticalLayout_2.addWidget(self.rdListadoDemandantes)
        self.rdListadoDemandados = QtGui.QRadioButton(self.groupBox)
        self.rdListadoDemandados.setObjectName("rdListadoDemandados")
        self.verticalLayout_2.addWidget(self.rdListadoDemandados)
        self.rdListadoActuaciones = QtGui.QRadioButton(self.groupBox)
        self.rdListadoActuaciones.setObjectName("rdListadoActuaciones")
        self.verticalLayout_2.addWidget(self.rdListadoActuaciones)
        self.rdEventosProximos = QtGui.QRadioButton(self.groupBox)
        self.rdEventosProximos.setObjectName("rdEventosProximos")
        self.verticalLayout_2.addWidget(self.rdEventosProximos)
        self.rdListadoJuzgados = QtGui.QRadioButton(self.groupBox)
        self.rdListadoJuzgados.setObjectName("rdListadoJuzgados")
        self.verticalLayout_2.addWidget(self.rdListadoJuzgados)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(AsistenteImpresionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(AsistenteImpresionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), AsistenteImpresionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), AsistenteImpresionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AsistenteImpresionDialog)

    def retranslateUi(self, AsistenteImpresionDialog):
        AsistenteImpresionDialog.setWindowTitle(QtGui.QApplication.translate("AsistenteImpresionDialog", "Asistente de impresión", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("AsistenteImpresionDialog", "¿Qué desea imprimir?", None, QtGui.QApplication.UnicodeUTF8))
        self.rdProceso.setToolTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime un proceso con toda su información detallada", None, QtGui.QApplication.UnicodeUTF8))
        self.rdProceso.setStatusTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime un proceso con toda su información detallada", None, QtGui.QApplication.UnicodeUTF8))
        self.rdProceso.setText(QtGui.QApplication.translate("AsistenteImpresionDialog", "Un proceso con toda su información", None, QtGui.QApplication.UnicodeUTF8))
        self.rdDemandante.setToolTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime un demandante con toda su información detallada", None, QtGui.QApplication.UnicodeUTF8))
        self.rdDemandante.setStatusTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime un demandante con toda su información detallada", None, QtGui.QApplication.UnicodeUTF8))
        self.rdDemandante.setText(QtGui.QApplication.translate("AsistenteImpresionDialog", "Un cliente con toda su información", None, QtGui.QApplication.UnicodeUTF8))
        self.rdDemandado.setToolTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime un demandado con toda su información detallada", None, QtGui.QApplication.UnicodeUTF8))
        self.rdDemandado.setStatusTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime un demandado con toda su información detallada", None, QtGui.QApplication.UnicodeUTF8))
        self.rdDemandado.setText(QtGui.QApplication.translate("AsistenteImpresionDialog", "Una contraparte con toda su información", None, QtGui.QApplication.UnicodeUTF8))
        self.rdJuzgado.setToolTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime un juzgado con toda su información detallada", None, QtGui.QApplication.UnicodeUTF8))
        self.rdJuzgado.setStatusTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime un juzgado con toda su información detallada", None, QtGui.QApplication.UnicodeUTF8))
        self.rdJuzgado.setText(QtGui.QApplication.translate("AsistenteImpresionDialog", "Un juzgado con toda la información", None, QtGui.QApplication.UnicodeUTF8))
        self.rdQR.setToolTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime un código QR que podrá ser escaneado desde la aplicación móvil para rápida referencia", None, QtGui.QApplication.UnicodeUTF8))
        self.rdQR.setStatusTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime un código QR que podrá ser escaneado desde la aplicación móvil para rápida referencia", None, QtGui.QApplication.UnicodeUTF8))
        self.rdQR.setText(QtGui.QApplication.translate("AsistenteImpresionDialog", "El código QR de un proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.rdListadoProcesos.setToolTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime una lista de procesos con información general de cada uno.", None, QtGui.QApplication.UnicodeUTF8))
        self.rdListadoProcesos.setStatusTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime una lista de procesos con información general de cada uno.", None, QtGui.QApplication.UnicodeUTF8))
        self.rdListadoProcesos.setText(QtGui.QApplication.translate("AsistenteImpresionDialog", "Listado de procesos", None, QtGui.QApplication.UnicodeUTF8))
        self.rdListadoDemandantes.setToolTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime una lista de demandantes con información general de cada uno.", None, QtGui.QApplication.UnicodeUTF8))
        self.rdListadoDemandantes.setStatusTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime una lista de demandantes con información general de cada uno.", None, QtGui.QApplication.UnicodeUTF8))
        self.rdListadoDemandantes.setText(QtGui.QApplication.translate("AsistenteImpresionDialog", "Listado de clientes", None, QtGui.QApplication.UnicodeUTF8))
        self.rdListadoDemandados.setToolTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime una lista de demandados con información general de cada uno.", None, QtGui.QApplication.UnicodeUTF8))
        self.rdListadoDemandados.setStatusTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime una lista de demandados con información general de cada uno.", None, QtGui.QApplication.UnicodeUTF8))
        self.rdListadoDemandados.setText(QtGui.QApplication.translate("AsistenteImpresionDialog", "Listado de contrapartes", None, QtGui.QApplication.UnicodeUTF8))
        self.rdListadoActuaciones.setToolTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime la lista de actuaciones de un proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.rdListadoActuaciones.setStatusTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime la lista de actuaciones de un proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.rdListadoActuaciones.setText(QtGui.QApplication.translate("AsistenteImpresionDialog", "Listado de actuaciones", None, QtGui.QApplication.UnicodeUTF8))
        self.rdEventosProximos.setToolTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime la lista de los eventos próximos de su calendario", None, QtGui.QApplication.UnicodeUTF8))
        self.rdEventosProximos.setStatusTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime la lista de los eventos próximos de su calendario", None, QtGui.QApplication.UnicodeUTF8))
        self.rdEventosProximos.setText(QtGui.QApplication.translate("AsistenteImpresionDialog", "Listado de Eventos Próximos", None, QtGui.QApplication.UnicodeUTF8))
        self.rdListadoJuzgados.setToolTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime una lista de juzgados con información general de cada uno.", None, QtGui.QApplication.UnicodeUTF8))
        self.rdListadoJuzgados.setStatusTip(QtGui.QApplication.translate("AsistenteImpresionDialog", "Imprime una lista de juzgados con información general de cada uno.", None, QtGui.QApplication.UnicodeUTF8))
        self.rdListadoJuzgados.setText(QtGui.QApplication.translate("AsistenteImpresionDialog", "Listado de juzgados", None, QtGui.QApplication.UnicodeUTF8))

