# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainApp.ui'
#
# Created: Tue Mar 27 00:19:49 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainApp(object):
    def setupUi(self, mainApp):
        mainApp.setObjectName("mainApp")
        mainApp.resize(800, 600)
        self.centralwidget = QtGui.QWidget(mainApp)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Plain)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 682, 545))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        mainApp.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Archivo = QtGui.QMenu(self.menubar)
        self.menu_Archivo.setObjectName("menu_Archivo")
        self.menu_Nuevo = QtGui.QMenu(self.menu_Archivo)
        self.menu_Nuevo.setObjectName("menu_Nuevo")
        self.menuCampo_Personalizado = QtGui.QMenu(self.menu_Nuevo)
        self.menuCampo_Personalizado.setObjectName("menuCampo_Personalizado")
        self.menuExportar = QtGui.QMenu(self.menu_Archivo)
        self.menuExportar.setObjectName("menuExportar")
        self.menuEditar = QtGui.QMenu(self.menubar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuSincronizar = QtGui.QMenu(self.menubar)
        self.menuSincronizar.setObjectName("menuSincronizar")
        mainApp.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainApp)
        self.statusbar.setObjectName("statusbar")
        mainApp.setStatusBar(self.statusbar)
        self.actionNuevoProceso = QtGui.QAction(mainApp)
        self.actionNuevoProceso.setObjectName("actionNuevoProceso")
        self.actionNuevaPlantilla = QtGui.QAction(mainApp)
        self.actionNuevaPlantilla.setObjectName("actionNuevaPlantilla")
        self.actionNuevoDemandante = QtGui.QAction(mainApp)
        self.actionNuevoDemandante.setObjectName("actionNuevoDemandante")
        self.actionNuevoDemandado = QtGui.QAction(mainApp)
        self.actionNuevoDemandado.setObjectName("actionNuevoDemandado")
        self.actionNuevoJuzgado = QtGui.QAction(mainApp)
        self.actionNuevoJuzgado.setObjectName("actionNuevoJuzgado")
        self.actionNuevaActuacion = QtGui.QAction(mainApp)
        self.actionNuevaActuacion.setObjectName("actionNuevaActuacion")
        self.actionNuevaCategoria = QtGui.QAction(mainApp)
        self.actionNuevaCategoria.setObjectName("actionNuevaCategoria")
        self.actionNuevoCampo_Proceso = QtGui.QAction(mainApp)
        self.actionNuevoCampo_Proceso.setObjectName("actionNuevoCampo_Proceso")
        self.actionNuevoCampo_Plantilla = QtGui.QAction(mainApp)
        self.actionNuevoCampo_Plantilla.setObjectName("actionNuevoCampo_Plantilla")
        self.actionNuevoCampo_Demandante = QtGui.QAction(mainApp)
        self.actionNuevoCampo_Demandante.setObjectName("actionNuevoCampo_Demandante")
        self.actionNuevoCampo_Demandado = QtGui.QAction(mainApp)
        self.actionNuevoCampo_Demandado.setObjectName("actionNuevoCampo_Demandado")
        self.actionNuevoCampo_Juzgado = QtGui.QAction(mainApp)
        self.actionNuevoCampo_Juzgado.setObjectName("actionNuevoCampo_Juzgado")
        self.actionNuevoCampo_Actuacion = QtGui.QAction(mainApp)
        self.actionNuevoCampo_Actuacion.setObjectName("actionNuevoCampo_Actuacion")
        self.actionImprimir = QtGui.QAction(mainApp)
        self.actionImprimir.setObjectName("actionImprimir")
        self.actionImportar = QtGui.QAction(mainApp)
        self.actionImportar.setObjectName("actionImportar")
        self.actionNuevoProceso_a_partir_de_Plantilla = QtGui.QAction(mainApp)
        self.actionNuevoProceso_a_partir_de_Plantilla.setObjectName("actionNuevoProceso_a_partir_de_Plantilla")
        self.actionArchivo_CSV = QtGui.QAction(mainApp)
        self.actionArchivo_CSV.setObjectName("actionArchivo_CSV")
        self.actionArchivo_de_Copia_de_Seguridad = QtGui.QAction(mainApp)
        self.actionArchivo_de_Copia_de_Seguridad.setObjectName("actionArchivo_de_Copia_de_Seguridad")
        self.actionCerrar = QtGui.QAction(mainApp)
        self.actionCerrar.setObjectName("actionCerrar")
        self.menuCampo_Personalizado.addAction(self.actionNuevoCampo_Proceso)
        self.menuCampo_Personalizado.addAction(self.actionNuevoCampo_Plantilla)
        self.menuCampo_Personalizado.addAction(self.actionNuevoCampo_Demandante)
        self.menuCampo_Personalizado.addAction(self.actionNuevoCampo_Demandado)
        self.menuCampo_Personalizado.addAction(self.actionNuevoCampo_Juzgado)
        self.menuCampo_Personalizado.addAction(self.actionNuevoCampo_Actuacion)
        self.menu_Nuevo.addAction(self.actionNuevoProceso)
        self.menu_Nuevo.addAction(self.actionNuevaPlantilla)
        self.menu_Nuevo.addAction(self.actionNuevoDemandante)
        self.menu_Nuevo.addAction(self.actionNuevoDemandado)
        self.menu_Nuevo.addAction(self.actionNuevoJuzgado)
        self.menu_Nuevo.addAction(self.actionNuevaActuacion)
        self.menu_Nuevo.addAction(self.actionNuevaCategoria)
        self.menu_Nuevo.addAction(self.menuCampo_Personalizado.menuAction())
        self.menu_Nuevo.addAction(self.actionNuevoProceso_a_partir_de_Plantilla)
        self.menuExportar.addAction(self.actionArchivo_CSV)
        self.menuExportar.addAction(self.actionArchivo_de_Copia_de_Seguridad)
        self.menu_Archivo.addAction(self.menu_Nuevo.menuAction())
        self.menu_Archivo.addAction(self.actionImprimir)
        self.menu_Archivo.addAction(self.menuExportar.menuAction())
        self.menu_Archivo.addAction(self.actionImportar)
        self.menu_Archivo.addSeparator()
        self.menu_Archivo.addAction(self.actionCerrar)
        self.menubar.addAction(self.menu_Archivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuSincronizar.menuAction())

        self.retranslateUi(mainApp)
        QtCore.QMetaObject.connectSlotsByName(mainApp)

    def retranslateUi(self, mainApp):
        mainApp.setWindowTitle(QtGui.QApplication.translate("mainApp", "Procesos Judiciales", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Archivo.setTitle(QtGui.QApplication.translate("mainApp", "&Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Nuevo.setTitle(QtGui.QApplication.translate("mainApp", "&Nuevo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCampo_Personalizado.setTitle(QtGui.QApplication.translate("mainApp", "Campo Personalizado", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExportar.setTitle(QtGui.QApplication.translate("mainApp", "Exportar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEditar.setTitle(QtGui.QApplication.translate("mainApp", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSincronizar.setTitle(QtGui.QApplication.translate("mainApp", "Sincronizar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoProceso.setText(QtGui.QApplication.translate("mainApp", "Proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevaPlantilla.setText(QtGui.QApplication.translate("mainApp", "Plantilla", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoDemandante.setText(QtGui.QApplication.translate("mainApp", "Demandante", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoDemandado.setText(QtGui.QApplication.translate("mainApp", "Demandado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoJuzgado.setText(QtGui.QApplication.translate("mainApp", "Juzgado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevaActuacion.setText(QtGui.QApplication.translate("mainApp", "Actuación", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevaCategoria.setText(QtGui.QApplication.translate("mainApp", "Categoría", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoCampo_Proceso.setText(QtGui.QApplication.translate("mainApp", "Campo Proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoCampo_Plantilla.setText(QtGui.QApplication.translate("mainApp", "Campo Plantilla", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoCampo_Plantilla.setToolTip(QtGui.QApplication.translate("mainApp", "Nuevo Campo Plantilla", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoCampo_Demandante.setText(QtGui.QApplication.translate("mainApp", "Campo Demandante", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoCampo_Demandante.setToolTip(QtGui.QApplication.translate("mainApp", "Nuevo Campo Demandante", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoCampo_Demandado.setText(QtGui.QApplication.translate("mainApp", "Campo Demandado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoCampo_Demandado.setToolTip(QtGui.QApplication.translate("mainApp", "Nuevo Campo Demandado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoCampo_Juzgado.setText(QtGui.QApplication.translate("mainApp", "Campo Juzgado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoCampo_Juzgado.setToolTip(QtGui.QApplication.translate("mainApp", "Nuevo Campo Juzgado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoCampo_Actuacion.setText(QtGui.QApplication.translate("mainApp", "Campo Actuacion", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoCampo_Actuacion.setToolTip(QtGui.QApplication.translate("mainApp", "Nuevo Campo Actuacion", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImprimir.setText(QtGui.QApplication.translate("mainApp", "Imprimir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImprimir.setShortcut(QtGui.QApplication.translate("mainApp", "Meta+P, Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportar.setText(QtGui.QApplication.translate("mainApp", "Importar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportar.setShortcut(QtGui.QApplication.translate("mainApp", "Meta+I, Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevoProceso_a_partir_de_Plantilla.setText(QtGui.QApplication.translate("mainApp", "Proceso a partir de Plantilla", None, QtGui.QApplication.UnicodeUTF8))
        self.actionArchivo_CSV.setText(QtGui.QApplication.translate("mainApp", "Archivo CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.actionArchivo_de_Copia_de_Seguridad.setText(QtGui.QApplication.translate("mainApp", "Archivo de Copia de Seguridad", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCerrar.setText(QtGui.QApplication.translate("mainApp", "Cerrar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCerrar.setToolTip(QtGui.QApplication.translate("mainApp", "Cierra la aplicación", None, QtGui.QApplication.UnicodeUTF8))

