# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nuevoProceso.ui'
#
# Created: Tue Feb  7 16:21:17 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_NuevoProceso(object):
    def setupUi(self, NuevoProceso):
        NuevoProceso.setObjectName("NuevoProceso")
        NuevoProceso.resize(325, 361)
        self.gridLayout_2 = QtGui.QGridLayout(NuevoProceso)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtGui.QGroupBox(NuevoProceso)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_11)
        self.lblDemandante = QtGui.QLabel(self.groupBox)
        self.lblDemandante.setCursor(QtCore.Qt.PointingHandCursor)
        self.lblDemandante.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lblDemandante.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lblDemandante.setObjectName("lblDemandante")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lblDemandante)
        self.lblDemandado = QtGui.QLabel(self.groupBox)
        self.lblDemandado.setCursor(QtCore.Qt.PointingHandCursor)
        self.lblDemandado.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lblDemandado.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lblDemandado.setObjectName("lblDemandado")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lblDemandado)
        self.lblJuzgado = QtGui.QLabel(self.groupBox)
        self.lblJuzgado.setCursor(QtCore.Qt.PointingHandCursor)
        self.lblJuzgado.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lblJuzgado.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lblJuzgado.setObjectName("lblJuzgado")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lblJuzgado)
        self.txtRadicado = QtGui.QLineEdit(self.groupBox)
        self.txtRadicado.setObjectName("txtRadicado")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtRadicado)
        self.txtRadicadoUnico = QtGui.QLineEdit(self.groupBox)
        self.txtRadicadoUnico.setObjectName("txtRadicadoUnico")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtRadicadoUnico)
        self.txtTipo = QtGui.QLineEdit(self.groupBox)
        self.txtTipo.setObjectName("txtTipo")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.txtTipo)
        self.txtEstado = QtGui.QLineEdit(self.groupBox)
        self.txtEstado.setObjectName("txtEstado")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.txtEstado)
        self.lblCategoria = QtGui.QLabel(self.groupBox)
        self.lblCategoria.setCursor(QtCore.Qt.PointingHandCursor)
        self.lblCategoria.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lblCategoria.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lblCategoria.setObjectName("lblCategoria")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.lblCategoria)
        self.sbPrioridad = QtGui.QSpinBox(self.groupBox)
        self.sbPrioridad.setObjectName("sbPrioridad")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.sbPrioridad)
        self.dteFecha = QtGui.QDateTimeEdit(self.groupBox)
        self.dteFecha.setObjectName("dteFecha")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.dteFecha)
        self.txtNotas = QtGui.QLineEdit(self.groupBox)
        self.txtNotas.setObjectName("txtNotas")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.txtNotas)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.btnAdd = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdd.sizePolicy().hasHeightForWidth())
        self.btnAdd.setSizePolicy(sizePolicy)
        self.btnAdd.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout.addWidget(self.btnAdd, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.line = QtGui.QFrame(NuevoProceso)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(NuevoProceso)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(NuevoProceso)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), NuevoProceso.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), NuevoProceso.reject)
        QtCore.QMetaObject.connectSlotsByName(NuevoProceso)

    def retranslateUi(self, NuevoProceso):
        NuevoProceso.setWindowTitle(QtGui.QApplication.translate("NuevoProceso", "Nuevo proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("NuevoProceso", "Ingrese los datos del nuevo proceso:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NuevoProceso", "Demandante:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("NuevoProceso", "Demandado:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("NuevoProceso", "Juzgado:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("NuevoProceso", "Radicado:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("NuevoProceso", "Radicado único:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("NuevoProceso", "Tipo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("NuevoProceso", "Estado:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("NuevoProceso", "Categoría:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("NuevoProceso", "Prioridad:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("NuevoProceso", "Fecha de creación:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("NuevoProceso", "Notas:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDemandante.setText(QtGui.QApplication.translate("NuevoProceso", "vacío", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDemandado.setText(QtGui.QApplication.translate("NuevoProceso", "vacío", None, QtGui.QApplication.UnicodeUTF8))
        self.lblJuzgado.setText(QtGui.QApplication.translate("NuevoProceso", "vacío", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCategoria.setText(QtGui.QApplication.translate("NuevoProceso", "Ninguna", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("NuevoProceso", "+", None, QtGui.QApplication.UnicodeUTF8))

