# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nuevaPersona.ui'
#
# Created: Mon Jan 23 21:10:26 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_NuevaPersona(object):
    def setupUi(self, NuevaPersona):
        NuevaPersona.setObjectName("NuevaPersona")
        NuevaPersona.resize(370, 234)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NuevaPersona.sizePolicy().hasHeightForWidth())
        NuevaPersona.setSizePolicy(sizePolicy)
        NuevaPersona.setMaximumSize(QtCore.QSize(16777215, 250))
        self.gridLayout = QtGui.QGridLayout(NuevaPersona)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtGui.QDialogButtonBox(NuevaPersona)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(NuevaPersona)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.lblNombre = QtGui.QLabel(self.groupBox)
        self.lblNombre.setObjectName("lblNombre")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblNombre)
        self.txtNombre = QtGui.QLineEdit(self.groupBox)
        self.txtNombre.setObjectName("txtNombre")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtNombre)
        self.lblCedula = QtGui.QLabel(self.groupBox)
        self.lblCedula.setObjectName("lblCedula")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblCedula)
        self.txtCedula = QtGui.QLineEdit(self.groupBox)
        self.txtCedula.setObjectName("txtCedula")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtCedula)
        self.lbltelefono = QtGui.QLabel(self.groupBox)
        self.lbltelefono.setObjectName("lbltelefono")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbltelefono)
        self.txtTelefono = QtGui.QLineEdit(self.groupBox)
        self.txtTelefono.setObjectName("txtTelefono")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtTelefono)
        self.lblDireccion = QtGui.QLabel(self.groupBox)
        self.lblDireccion.setObjectName("lblDireccion")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblDireccion)
        self.txtDireccion = QtGui.QLineEdit(self.groupBox)
        self.txtDireccion.setObjectName("txtDireccion")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtDireccion)
        self.lblCorreo = QtGui.QLabel(self.groupBox)
        self.lblCorreo.setObjectName("lblCorreo")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblCorreo)
        self.txtCorreo = QtGui.QLineEdit(self.groupBox)
        self.txtCorreo.setObjectName("txtCorreo")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtCorreo)
        self.lblNotas = QtGui.QLabel(self.groupBox)
        self.lblNotas.setObjectName("lblNotas")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblNotas)
        self.txtNotas = QtGui.QLineEdit(self.groupBox)
        self.txtNotas.setObjectName("txtNotas")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.txtNotas)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.line = QtGui.QFrame(NuevaPersona)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.lblNombre.setBuddy(self.txtNombre)
        self.lblCedula.setBuddy(self.txtCedula)
        self.lbltelefono.setBuddy(self.txtTelefono)
        self.lblDireccion.setBuddy(self.txtDireccion)
        self.lblCorreo.setBuddy(self.txtCorreo)
        self.lblNotas.setBuddy(self.txtNotas)

        self.retranslateUi(NuevaPersona)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), NuevaPersona.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), NuevaPersona.reject)
        QtCore.QMetaObject.connectSlotsByName(NuevaPersona)

    def retranslateUi(self, NuevaPersona):
        NuevaPersona.setWindowTitle(QtGui.QApplication.translate("NuevaPersona", "Nueva persona", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("NuevaPersona", "Ingrese la información de la nueva persona:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNombre.setText(QtGui.QApplication.translate("NuevaPersona", "Nombre:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCedula.setText(QtGui.QApplication.translate("NuevaPersona", "Cédula:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbltelefono.setText(QtGui.QApplication.translate("NuevaPersona", "Teléfono:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDireccion.setText(QtGui.QApplication.translate("NuevaPersona", "Dirección:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCorreo.setText(QtGui.QApplication.translate("NuevaPersona", "Correo:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNotas.setText(QtGui.QApplication.translate("NuevaPersona", "Notas:", None, QtGui.QApplication.UnicodeUTF8))

