# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nuevaPersona.ui'
#
# Created: Thu Jan 19 17:33:37 2012
#      by: pyside-uic 0.2.13 running on PySide 1.0.8
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_nuevaPersona(object):
    def setupUi(self, nuevaPersona):
        nuevaPersona.setObjectName("nuevaPersona")
        nuevaPersona.resize(281, 224)
        self.gridLayout = QtGui.QGridLayout(nuevaPersona)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.lblNombre = QtGui.QLabel(nuevaPersona)
        self.lblNombre.setObjectName("lblNombre")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblNombre)
        self.txtNombre = QtGui.QLineEdit(nuevaPersona)
        self.txtNombre.setObjectName("txtNombre")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtNombre)
        self.lblCedula = QtGui.QLabel(nuevaPersona)
        self.lblCedula.setObjectName("lblCedula")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblCedula)
        self.txtCedula = QtGui.QLineEdit(nuevaPersona)
        self.txtCedula.setObjectName("txtCedula")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtCedula)
        self.lbltelefono = QtGui.QLabel(nuevaPersona)
        self.lbltelefono.setObjectName("lbltelefono")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbltelefono)
        self.txtTelefono = QtGui.QLineEdit(nuevaPersona)
        self.txtTelefono.setObjectName("txtTelefono")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtTelefono)
        self.lblDireccion = QtGui.QLabel(nuevaPersona)
        self.lblDireccion.setObjectName("lblDireccion")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblDireccion)
        self.txtDireccion = QtGui.QLineEdit(nuevaPersona)
        self.txtDireccion.setObjectName("txtDireccion")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtDireccion)
        self.lblCorreo = QtGui.QLabel(nuevaPersona)
        self.lblCorreo.setObjectName("lblCorreo")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblCorreo)
        self.txtCorreo = QtGui.QLineEdit(nuevaPersona)
        self.txtCorreo.setObjectName("txtCorreo")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtCorreo)
        self.lblNotas = QtGui.QLabel(nuevaPersona)
        self.lblNotas.setObjectName("lblNotas")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblNotas)
        self.txtNotas = QtGui.QLineEdit(nuevaPersona)
        self.txtNotas.setObjectName("txtNotas")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.txtNotas)
        self.gridLayout.addLayout(self.formLayout, 1, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(nuevaPersona)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.lblNombre.setBuddy(self.txtNombre)
        self.lblCedula.setBuddy(self.txtCedula)
        self.lbltelefono.setBuddy(self.txtTelefono)
        self.lblDireccion.setBuddy(self.txtDireccion)
        self.lblCorreo.setBuddy(self.txtCorreo)
        self.lblNotas.setBuddy(self.txtNotas)

        self.retranslateUi(nuevaPersona)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), nuevaPersona.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), nuevaPersona.reject)
        QtCore.QMetaObject.connectSlotsByName(nuevaPersona)
        nuevaPersona.setTabOrder(self.txtNombre, self.txtCedula)
        nuevaPersona.setTabOrder(self.txtCedula, self.txtTelefono)
        nuevaPersona.setTabOrder(self.txtTelefono, self.txtDireccion)
        nuevaPersona.setTabOrder(self.txtDireccion, self.txtCorreo)
        nuevaPersona.setTabOrder(self.txtCorreo, self.txtNotas)
        nuevaPersona.setTabOrder(self.txtNotas, self.buttonBox)

    def retranslateUi(self, nuevaPersona):
        nuevaPersona.setWindowTitle(QtGui.QApplication.translate("nuevaPersona", "Nueva persona", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNombre.setText(QtGui.QApplication.translate("nuevaPersona", "Nombre:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCedula.setText(QtGui.QApplication.translate("nuevaPersona", "Cédula:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbltelefono.setText(QtGui.QApplication.translate("nuevaPersona", "Teléfono:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDireccion.setText(QtGui.QApplication.translate("nuevaPersona", "Dirección:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCorreo.setText(QtGui.QApplication.translate("nuevaPersona", "Correo:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNotas.setText(QtGui.QApplication.translate("nuevaPersona", "Notas:", None, QtGui.QApplication.UnicodeUTF8))

