# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verActuacion.ui'
#
# Created: Thu Jan 26 08:10:08 2012
#      by: pyside-uic 0.2.13 running on PySide 1.0.7
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_VerActuacion(object):
    def setupUi(self, VerActuacion):
        VerActuacion.setObjectName("VerActuacion")
        VerActuacion.resize(364, 179)
        self.gridLayout = QtGui.QGridLayout(VerActuacion)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(VerActuacion)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(-1, -1, 10, -1)
        self.formLayout.setObjectName("formLayout")
        self.lbl1 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl1.sizePolicy().hasHeightForWidth())
        self.lbl1.setSizePolicy(sizePolicy)
        self.lbl1.setObjectName("lbl1")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl1)
        self.lblJuzgado = QtGui.QLabel(self.groupBox)
        self.lblJuzgado.setText("")
        self.lblJuzgado.setObjectName("lblJuzgado")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lblJuzgado)
        self.lbl2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl2.sizePolicy().hasHeightForWidth())
        self.lbl2.setSizePolicy(sizePolicy)
        self.lbl2.setObjectName("lbl2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl2)
        self.lbl3 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl3.sizePolicy().hasHeightForWidth())
        self.lbl3.setSizePolicy(sizePolicy)
        self.lbl3.setObjectName("lbl3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl3)
        self.lbl4 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl4.sizePolicy().hasHeightForWidth())
        self.lbl4.setSizePolicy(sizePolicy)
        self.lbl4.setObjectName("lbl4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl4)
        self.lblDescripcion = QtGui.QLabel(self.groupBox)
        self.lblDescripcion.setText("")
        self.lblDescripcion.setObjectName("lblDescripcion")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lblDescripcion)
        self.dteFecha = QtGui.QDateTimeEdit(self.groupBox)
        self.dteFecha.setEnabled(False)
        self.dteFecha.setObjectName("dteFecha")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.dteFecha)
        self.dteFechaProxima = QtGui.QDateTimeEdit(self.groupBox)
        self.dteFechaProxima.setEnabled(False)
        self.dteFechaProxima.setObjectName("dteFechaProxima")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.dteFechaProxima)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(VerActuacion)
        QtCore.QMetaObject.connectSlotsByName(VerActuacion)

    def retranslateUi(self, VerActuacion):
        VerActuacion.setWindowTitle(QtGui.QApplication.translate("VerActuacion", "Ver Actuación", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl1.setText(QtGui.QApplication.translate("VerActuacion", "Juzgado:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblJuzgado.setToolTip(QtGui.QApplication.translate("VerActuacion", "El juzgado donde fue dictada la actuación", None, QtGui.QApplication.UnicodeUTF8))
        self.lblJuzgado.setStatusTip(QtGui.QApplication.translate("VerActuacion", "El juzgado donde fue dictada la actuación", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl2.setText(QtGui.QApplication.translate("VerActuacion", "Fecha:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl3.setText(QtGui.QApplication.translate("VerActuacion", "Fecha Próxima:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl4.setText(QtGui.QApplication.translate("VerActuacion", "Descripción:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDescripcion.setToolTip(QtGui.QApplication.translate("VerActuacion", "La descripción de la actuación", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDescripcion.setStatusTip(QtGui.QApplication.translate("VerActuacion", "La descripción de la actuación", None, QtGui.QApplication.UnicodeUTF8))
        self.dteFecha.setToolTip(QtGui.QApplication.translate("VerActuacion", "La fecha donde fue dictada la actuación", None, QtGui.QApplication.UnicodeUTF8))
        self.dteFecha.setStatusTip(QtGui.QApplication.translate("VerActuacion", "La fecha donde fue dictada la actuación", None, QtGui.QApplication.UnicodeUTF8))
        self.dteFechaProxima.setToolTip(QtGui.QApplication.translate("VerActuacion", "La fecha del siguiente evento en la actuación", None, QtGui.QApplication.UnicodeUTF8))
        self.dteFechaProxima.setStatusTip(QtGui.QApplication.translate("VerActuacion", "La fecha del siguiente evento en la actuación", None, QtGui.QApplication.UnicodeUTF8))

