# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verPlantilla.ui'
#
# Created: Mon Mar 19 22:45:40 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_VerPlantilla(object):
    def setupUi(self, VerPlantilla):
        VerPlantilla.setObjectName("VerPlantilla")
        VerPlantilla.resize(292, 292)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VerPlantilla.sizePolicy().hasHeightForWidth())
        VerPlantilla.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(VerPlantilla)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(VerPlantilla)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(-1, -1, 10, -1)
        self.formLayout.setObjectName("formLayout")
        self.lbl0 = QtGui.QLabel(self.groupBox)
        self.lbl0.setObjectName("lbl0")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl0)
        self.lblNombre = QtGui.QLabel(self.groupBox)
        self.lblNombre.setText("")
        self.lblNombre.setObjectName("lblNombre")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lblNombre)
        self.lbl1 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl1.sizePolicy().hasHeightForWidth())
        self.lbl1.setSizePolicy(sizePolicy)
        self.lbl1.setObjectName("lbl1")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl1)
        self.lblDemandante = QtGui.QLabel(self.groupBox)
        self.lblDemandante.setText("")
        self.lblDemandante.setObjectName("lblDemandante")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lblDemandante)
        self.lbl2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl2.sizePolicy().hasHeightForWidth())
        self.lbl2.setSizePolicy(sizePolicy)
        self.lbl2.setObjectName("lbl2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl2)
        self.lblDemandado = QtGui.QLabel(self.groupBox)
        self.lblDemandado.setText("")
        self.lblDemandado.setObjectName("lblDemandado")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lblDemandado)
        self.lbl4 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl4.sizePolicy().hasHeightForWidth())
        self.lbl4.setSizePolicy(sizePolicy)
        self.lbl4.setObjectName("lbl4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl4)
        self.lblJuzgado = QtGui.QLabel(self.groupBox)
        self.lblJuzgado.setText("")
        self.lblJuzgado.setObjectName("lblJuzgado")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lblJuzgado)
        self.lbl5 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl5.sizePolicy().hasHeightForWidth())
        self.lbl5.setSizePolicy(sizePolicy)
        self.lbl5.setObjectName("lbl5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl5)
        self.lblRadicado = QtGui.QLabel(self.groupBox)
        self.lblRadicado.setText("")
        self.lblRadicado.setObjectName("lblRadicado")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lblRadicado)
        self.lbl6 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl6.sizePolicy().hasHeightForWidth())
        self.lbl6.setSizePolicy(sizePolicy)
        self.lbl6.setObjectName("lbl6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lbl6)
        self.lblRadicadoUnico = QtGui.QLabel(self.groupBox)
        self.lblRadicadoUnico.setText("")
        self.lblRadicadoUnico.setObjectName("lblRadicadoUnico")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lblRadicadoUnico)
        self.lbl7 = QtGui.QLabel(self.groupBox)
        self.lbl7.setObjectName("lbl7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lbl7)
        self.lblCategoria = QtGui.QLabel(self.groupBox)
        self.lblCategoria.setText("")
        self.lblCategoria.setObjectName("lblCategoria")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lblCategoria)
        self.lbl8 = QtGui.QLabel(self.groupBox)
        self.lbl8.setObjectName("lbl8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.lbl8)
        self.lblEstado = QtGui.QLabel(self.groupBox)
        self.lblEstado.setText("")
        self.lblEstado.setObjectName("lblEstado")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.lblEstado)
        self.lbl9 = QtGui.QLabel(self.groupBox)
        self.lbl9.setObjectName("lbl9")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.lbl9)
        self.lblTipo = QtGui.QLabel(self.groupBox)
        self.lblTipo.setText("")
        self.lblTipo.setObjectName("lblTipo")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.lblTipo)
        self.lbl11 = QtGui.QLabel(self.groupBox)
        self.lbl11.setObjectName("lbl11")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.lbl11)
        self.lblPrioridad = QtGui.QLabel(self.groupBox)
        self.lblPrioridad.setText("")
        self.lblPrioridad.setObjectName("lblPrioridad")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.lblPrioridad)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lbl10 = QtGui.QLabel(self.groupBox)
        self.lbl10.setObjectName("lbl10")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl10)
        self.lblNotas = QtGui.QTextBrowser(self.groupBox)
        self.lblNotas.setObjectName("lblNotas")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lblNotas)
        self.gridLayout_2.addLayout(self.formLayout_2, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(VerPlantilla)
        QtCore.QMetaObject.connectSlotsByName(VerPlantilla)

    def retranslateUi(self, VerPlantilla):
        VerPlantilla.setWindowTitle(QtGui.QApplication.translate("VerPlantilla", "Ver Plantilla", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl0.setText(QtGui.QApplication.translate("VerPlantilla", "Nombre:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNombre.setToolTip(QtGui.QApplication.translate("VerPlantilla", "Nombre descriptivo para la plantilla", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNombre.setStatusTip(QtGui.QApplication.translate("VerPlantilla", "Nombre descriptivo para la plantilla", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl1.setText(QtGui.QApplication.translate("VerPlantilla", "Demandante:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDemandante.setToolTip(QtGui.QApplication.translate("VerPlantilla", "El nombre del demandante", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDemandante.setStatusTip(QtGui.QApplication.translate("VerPlantilla", "El nombre del demandante", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl2.setText(QtGui.QApplication.translate("VerPlantilla", "Demandado:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDemandado.setToolTip(QtGui.QApplication.translate("VerPlantilla", "El nombre del demandado", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDemandado.setStatusTip(QtGui.QApplication.translate("VerPlantilla", "El nombre del demandado", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl4.setText(QtGui.QApplication.translate("VerPlantilla", "Juzgado:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblJuzgado.setToolTip(QtGui.QApplication.translate("VerPlantilla", "El nombre del juzgado del proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.lblJuzgado.setStatusTip(QtGui.QApplication.translate("VerPlantilla", "El nombre del juzgado del proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl5.setText(QtGui.QApplication.translate("VerPlantilla", "Radicado:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRadicado.setToolTip(QtGui.QApplication.translate("VerPlantilla", "El radicado del proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRadicado.setStatusTip(QtGui.QApplication.translate("VerPlantilla", "El radicado del proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl6.setText(QtGui.QApplication.translate("VerPlantilla", "Radicado Único:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRadicadoUnico.setToolTip(QtGui.QApplication.translate("VerPlantilla", "El radicado único del proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRadicadoUnico.setStatusTip(QtGui.QApplication.translate("VerPlantilla", "El radicado único del proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl7.setText(QtGui.QApplication.translate("VerPlantilla", "Categoría:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCategoria.setToolTip(QtGui.QApplication.translate("VerPlantilla", "La categoría donde está el proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCategoria.setStatusTip(QtGui.QApplication.translate("VerPlantilla", "La categoría donde está el proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl8.setText(QtGui.QApplication.translate("VerPlantilla", "Estado:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEstado.setToolTip(QtGui.QApplication.translate("VerPlantilla", "El estado del proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEstado.setStatusTip(QtGui.QApplication.translate("VerPlantilla", "El estado del proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl9.setText(QtGui.QApplication.translate("VerPlantilla", "Tipo:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTipo.setToolTip(QtGui.QApplication.translate("VerPlantilla", "El tipo de proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTipo.setStatusTip(QtGui.QApplication.translate("VerPlantilla", "El tipo de proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl11.setText(QtGui.QApplication.translate("VerPlantilla", "Prioridad:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPrioridad.setToolTip(QtGui.QApplication.translate("VerPlantilla", "La prioridad del proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPrioridad.setStatusTip(QtGui.QApplication.translate("VerPlantilla", "La prioridad del proceso", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl10.setText(QtGui.QApplication.translate("VerPlantilla", "Notas:", None, QtGui.QApplication.UnicodeUTF8))

